# Generated by Django 5.2 on 2025-04-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quote', models.TextField(help_text='Das Kundenzitat')),
                ('author', models.CharField(help_text='Name des Kunden', max_length=100)),
                ('event', models.CharField(help_text="Art des Events (z.B. 'Hochzeit im Schloss Bellevue')", max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Profilbild des Kunden', null=True, upload_to='testimonials/')),
                ('is_active', models.BooleanField(default=True, help_text='Testimonial auf der Webseite anzeigen?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Reihenfolge (niedrigere Zahlen erscheinen zuerst)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
