# Generated by Django 5.2 on 2025-04-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name des Kunden', max_length=100)),
                ('email', models.EmailField(help_text='E-Mail-Adresse des Kunden', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Telefonnummer des Kunden', max_length=50, null=True)),
                ('event_type', models.CharField(choices=[('hochzeit', 'Hochzeit'), ('firmenfeier', 'Firmenfeier'), ('geburtstag', 'Geburtstag'), ('andere', 'Andere')], default='andere', help_text='Art des Events', max_length=20)),
                ('event_date', models.DateField(blank=True, help_text='Datum des Events', null=True)),
                ('message', models.TextField(help_text='Nachricht des Kunden')),
                ('status', models.CharField(choices=[('neu', 'Neu'), ('in_bearbeitung', 'In Bearbeitung'), ('beantwortet', 'Beantwortet'), ('archiviert', 'Archiviert')], default='neu', help_text='Bearbeitungsstatus', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Interne Notizen (für den Kunden nicht sichtbar)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kontaktanfrage',
                'verbose_name_plural': 'Kontaktanfragen',
                'ordering': ['-created_at'],
            },
        ),
    ]
