# Generated by Django 5.2 on 2025-04-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(choices=[('gallery', 'Galerie'), ('services', 'Leistungen'), ('testimonials', 'Testimonials'), ('about', 'Über Uns'), ('contact', 'Kontakt')], help_text='Abschnitt der Website', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Titel des Abschnitts', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Untertitel/Beschreibung des Abschnitts', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Abschnitt anzeigen?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Abschnitt',
                'verbose_name_plural': 'Website Abschnitte',
            },
        ),
    ]
