# Generated by Django 5.2 on 2025-04-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_websitesection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='featured',
            field=models.BooleanField(default=False, help_text='Auf der Startseite anzeigen?'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='height',
            field=models.IntegerField(default=600, help_text='Höhe des Bildes'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='span',
            field=models.CharField(default='col-span-1', help_text="Grid-Span-Klasse (z.B. 'col-span-1 md:col-span-2')", max_length=50),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='width',
            field=models.IntegerField(default=800, help_text='Breite des Bildes'),
        ),
    ]
